### PR TITLE
Explicitly implement isValidX

### LINKED ISSUE #385: Bug in rational/int equality
There seems to be a bug in rational/int equality. Probably something going wrong with the "cooperative equality" code. I tested this with spire 0.8.2 to make sure it was not recently introduced:

```scala
scala>  Rational("18446744073709551614") == -2
res1: Boolean = true

scala>  Rational("18446744073709551614").isValidInt
res2: Boolean = true
```

The given number is Rational(Long.MaxValue) * 2. In case that helps to track it down.

### PR DESCRIPTION
**Pull request by rklaehn**
The implementation in the base class will not work for rationals.

x.toLong == x.toInt does not guarantee that the value is within int range
for values that can become larger than a long.

Fixes #385

However, there should be some tests to make sure this does not happen again. Also, SafeLong seems to suffer from similar issues which will have to be tracked separately.

### CODE REVIEW

File: core/src/main/scala/spire/math/Rational.scala [hunk 1]
```diff
@@ -559,6 +559,16 @@ private[math] object LongRationals extends Rationals[Long] {
 
     override def signum: Int = java.lang.Long.signum(n)
 
+    override def isWhole: Boolean = n == 1L
```
Comment (non) [inline core/src/main/scala/spire/math/Rational.scala]: Shouldn't this be `d == 1L`?

File: core/src/main/scala/spire/math/Rational.scala [hunk 2]
```diff
@@ -879,6 +889,14 @@ private[math] object BigRationals extends Rationals[BigInt] {
 
     override def signum: Int = n.signum
 
+    override def isValidChar = false
```
Comment (non) [inline core/src/main/scala/spire/math/Rational.scala]: Wouldn't you need to override `isWhole` in this case as well? Very large integers should still be whole numbers.

File: core/src/main/scala/spire/math/Rational.scala (hunk 1 above)
Comment (rklaehn) [inline core/src/main/scala/spire/math/Rational.scala]: You are right, of course.

File: core/src/main/scala/spire/math/Rational.scala (hunk 2 above)
Comment (rklaehn) [inline core/src/main/scala/spire/math/Rational.scala]: For BigRational I keep the isWhole implementation from RationalLike for now.

**Comment by non** [comment]
Looks great. Thanks!
